### ISSUE TITLE
Panic on bad gossip (?) response

### ISSUE THREAD

**Issue by freight-stack** [cryptoscope/ssb#47]
The go-sbot panics when an error is returned without header flag 'isEndOrError' set to true.

```
level=debug time=2020-04-24T13:53:51.770526929+02:00 caller=new.go:218 module=sbot invite="not for us"
level=warn time=2020-04-24T13:53:51.770591321+02:00 caller=auth.go:38 module=sbot module=graph module=graph msg="authbypass - trust on first use"
time=2020-04-24T13:53:51.770782005+02:00 caller=handler.go:68 module=sbot plugin=gossip remote=<@zwWh.ed25519> event=gossiprx handleConnect="oops - dont have my own feed. requesting..."
level=debug time=2020-04-24T13:53:51.772856289+02:00 caller=fetch.go:201 module=sbot plugin=gossip event=gossiprx fr=<@Seaq.ed25519> latest=0 received=1 took=2.046944ms
panic: runtime error: slice bounds out of range [:15] with capacity 8

goroutine 81 [running]:
go.cryptoscope.co/ssb/message/legacy.Verify(0xc000120b18, 0x4, 0x8, 0x0, 0xc00009ac00, 0x0, 0xc000204b28, 0xc00010f7a6)
        /home/freight/src/ssb/message/legacy/verify.go:43 +0xaf9
go.cryptoscope.co/ssb/message.legacyVerify.Verify(0x0, 0xce4ca0, 0xc000199b20, 0x7b8a00, 0xc00010f808, 0xc00010f7a0, 0x3)
        /home/freight/src/ssb/message/drains.go:55 +0x8f
go.cryptoscope.co/ssb/message.(*streamDrain).Pour(0xc000080ac0, 0xf3fbe0, 0xc000204960, 0xce4ca0, 0xc000199b20, 0xc000199b20, 0x0)
        /home/freight/src/ssb/message/drains.go:116 +0x65
go.cryptoscope.co/luigi/mfr.(*sinkMap).Pour(0xc000199a00, 0xf3fbe0, 0xc000204960, 0xce4ca0, 0xc000199b20, 0x0, 0x0)
        /home/freight/src/go/pkg/mod/go.cryptoscope.co/luigi@v0.3.5/mfr/map.go:36 +0xba
go.cryptoscope.co/luigi.Pump(0xf3fbe0, 0xc000204960, 0xf36320, 0xc000199a00, 0xf2cec0, 0xc0000f29c0, 0x1, 0x1)
        /home/freight/src/go/pkg/mod/go.cryptoscope.co/luigi@v0.3.5/stream.go:65 +0x11f
go.cryptoscope.co/ssb/plugins/gossip.(*handler).fetchFeed(0xc00022a0d0, 0xf3fba0, 0xc00003a120, 0xc000104ae0, 0xf46e20, 0xc0000f2510, 0xbfa0d2b3edf194aa, 0x91b90d36, 0x16d40a0, 0x0, ...)
        /home/freight/src/ssb/plugins/gossip/fetch.go:240 +0x955
go.cryptoscope.co/ssb/plugins/gossip.(*handler).HandleConnect(0xc00022a0d0, 0xf3fba0, 0xc00003a120, 0xf46e20, 0xc0000f2510)
        /home/freight/src/ssb/plugins/gossip/handler.go:69 +0xdae
go.cryptoscope.co/muxrpc.(*HandlerMux).HandleConnect.func1(0xf3fba0, 0xc00003a120, 0xf46e20, 0xc0000f2510, 0xc0001204c0, 0xf366e0, 0xc00022a0d0)
        /home/freight/src/go/pkg/mod/go.cryptoscope.co/muxrpc@v1.5.4-0.20191205134222-b1563255bffa/handler.go:58 +0x59
created by go.cryptoscope.co/muxrpc.(*HandlerMux).HandleConnect
        /home/freight/src/go/pkg/mod/go.cryptoscope.co/muxrpc@v1.5.4-0.20191205134222-b1563255bffa/handler.go:56 +0x127
```

**Comment by cryptix** [comment]
Thanks for reporting this @freight-stack!

Should be fixed now, read the commit message for the gory details.
